[system]
compatible=jetson-agx-orin
bootloader=custom
statusfile=/var/lib/rauc/status

[keyring]
path=/etc/rauc/cambrian-works.cert.pem

[handlers]
bootloader-custom-backend=/usr/lib/rauc/backend/jetson-boot-backend

[slot.rootfs.0]
device=/dev/mmcblk0p1
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p2
type=ext4
bootname=B
