#@TYPE: Machine
#@NAME: Jetson AGX Orin dev kit (P3701-0005)
#@DESCRIPTION: Jetson AGX Orin dev kit target for GigRouter platform.

TEGRA_BOARDSKU ?= "0005"
PARTITION_LAYOUT_TEMPLATE_DEFAULT ?= "flash_t234_qspi_sdmmc.xml"

PREFERRED_PROVIDER_virtual/sh = "bash"
PREFERRED_PROVIDER_base-utils = "coreutils"
VIRTUAL-RUNTIME_base-utils = "coreutils"

MACHINEOVERRIDES =. "gig:"
DTBFILE = "tegra234-p3737-0000+p3701-0005-nv.dtb"
KERNEL_DEVICETREE = "${DTBFILE}"

require conf/machine/include/agx-orin.inc
